<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/Day30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 30

The Breast Cancer Data was loaded into the all_data variable.

Create a DataFrame from the all_data array and assign to df variable. Set column names using value for the key 'feature_names' of raw_data + set target variable name as 'target' as shown below.

In response, print the first five rows of this DataFrame to the console.


Expected result:


       mean radius  mean texture  mean perimeter  mean area  mean smoothness  ...  worst concavity  worst concave points  worst symmetry  worst fractal dimension  target
    0        17.99         10.38          122.80     1001.0          0.11840  ...           0.7119                0.2654          0.4601                  0.11890     0.0
    1        20.57         17.77          132.90     1326.0          0.08474  ...           0.2416                0.1860          0.2750                  0.08902     0.0
    2        19.69         21.25          130.00     1203.0          0.10960  ...           0.4504                0.2430          0.3613                  0.08758     0.0
    3        11.42         20.38           77.58      386.1          0.14250  ...           0.6869                0.2575          0.6638                  0.17300     0.0
    4        20.29         14.34          135.10     1297.0          0.10030  ...           0.4000                0.1625          0.2364                  0.07678     0.0
     
    [5 rows x 31 columns]

In [24]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [26]:

lbc = load_breast_cancer()
data = lbc['data']
target = lbc['target']

all_data = np.c_[data,target]

df = pd.DataFrame(
    data=all_data, 
    columns=list(lbc['feature_names']) + ['target']
)

In [28]:

pd.set_option('display.max_columns', 10)
pd.set_option('display.width', 200)
np.set_printoptions(precision=2, suppress=True, linewidth=100)

df

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  ...  worst concavity  worst concave points  worst symmetry  worst fractal dimension  target
0          17.99         10.38          122.80     1001.0          0.11840  ...           0.7119                0.2654          0.4601                  0.11890     0.0
1          20.57         17.77          132.90     1326.0          0.08474  ...           0.2416                0.1860          0.2750                  0.08902     0.0
2          19.69         21.25          130.00     1203.0          0.10960  ...           0.4504                0.2430          0.3613                  0.08758     0.0
3          11.42         20.38           77.58      386.1          0.14250  ...           0.6869                0.2575          0.6638                  0.17300     0.0
4          20.29         14.34          135.10     1297.0          0.10030  ...           0.4000                0.1625          0.2364                  0.07678     0.0
..           ...           ...             ...        ...              ...  ...              ...                   ...             ...                      ...     ...
564        21.56         22.39          142.00     1479.0          0.11100  ...           0.4107                0.2216          0.2060                  0.07115     0.0
565        20.13         28.25          131.20     1261.0          0.09780  ...           0.3215                0.1628          0.2572                  0.06637     0.0
566        16.60         28.08          108.30      858.1          0.08455  ...           0.3403                0.1418          0.2218                  0.07820     0.0
567        20.60         29.33          140.10     1265.0          0.11780  ...           0.9387                0.2650          0.4087                  0.12400     0.0
568         7.76         24.54           47.92      181.0          0.05263  ...           0.0000                0.0000          0.2871                  0.07039     1.0

[569 rows x 31 columns]